### ISSUE TITLE
Rewrite in Vue.js 3 with Vite and QUASAR with BEX

### ISSUE THREAD

**Issue by pbek** [qownnotes/web-companion#56]
Since all the libraries are very deprecated and the already gone node14 is needed to build the application, I'm in the process of rewriting the whole browser extension in Vue.js 3 with Vite and QUASAR with BEX.

## Todo

- [x] Bookmark list with pagination
- [x] Note search
- [x] Note folder switching
- [x] Tags
- [x] Add bookmark
- [x] "Records per page", search and tags persisted
    - <https://codepen.io/clixmat/pen/NZyRgW>
- [x] Firefox consent dialog
- [x] Option page
    - [x] Showing options
    - [x] Storing options
- [x] Select all search text after loading, to be able to overwrite it easily
- [x] Remove `vite-plugin-vue-i18n` and `vue-i18n`
- [x] Snackbar replacement
    - <https://quasar.dev/quasar-plugins/notify/>
- [x] Open all bookmarks
- [x] Bookmark all open tabs
- [x] Import browser bookmarks
- [x] Link to web clipper in Menu
- [x] tabindex to traverse through bookmark list
- [x] Tag filtering: "x" button does not remove all tags from the filter
- [x] Screenshot tool
    - [x] Support Chrome
    - [x] Support Firefox
- [x] Webclipper tool
    - [x] Whole webpage
        - [x] Support Chrome
        - [x] Support Firefox
    - [x] Selection
        - [x] Support Chrome
        - [x] Support Firefox
- [x] Toolbar shortcut
    - [x] Support Chrome
    - [x] Support Firefox
- [x] Improve layout
    - [x] Better colors
    - [x] Move note folder selector and search input to header
- [x] Test everything in Firefox, because APIs might differ!
- [x] Add mechanism to use different version numbers for Chrome (or try to use the same with Firefox)
- [x] New screenshots for <https://www.qownnotes.org/getting-started/browser-extension.html>
    - [x] Mention <https://discourse.mozilla.org/t/browser-tabs-capturevisibletab-not-working-in-firefox-for-mv3/122965/2> for Firefox
- [x] Create release build process

**Comment by pbek** [comment]
## 2024.2.0
- the extension was completely **rewritten in Vue.js 3 with Vite using QUASAR with BEX**
 (for [#56](https://github.com/qownnotes/web-companion/issues/56))
  - also both the Chrome and Firefox extensions are now using manifest version 3

**Comment by pbek** [comment]
## 2024.2.1
- an issue with the columns in the bookmarks list was fixed
  (for [#56](https://github.com/qownnotes/web-companion/issues/56))
- the minimum version for Firefox was raised to 109, because of manifest version 3
  (for [#56](https://github.com/qownnotes/web-companion/issues/56))
- `host_permissions` were removed from the manifest file for Chrome, because they are not needed
  (for [#56](https://github.com/qownnotes/web-companion/issues/56))
- added more translation
